NAME: wandb
LAST DEPLOYED: Sun May 28 23:10:34 2023
NAMESPACE: default
STATUS: pending-install
REVISION: 1
HOOKS:
---
# Source: wandb/charts/webservice/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "wandb-webservice-test-connection"
  labels:
    helm.sh/chart: webservice-0.1.0
    app.kubernetes.io/name: webservice
    app.kubernetes.io/instance: wandb
    app.kubernetes.io/version: "0.33.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['wandb-webservice:8080']
  restartPolicy: Never
MANIFEST:
---
# Source: wandb/charts/mysql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wandb-mysql
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.10.1
    app.kubernetes.io/instance: wandb
    app.kubernetes.io/managed-by: Helm
  annotations:
automountServiceAccountToken: true
secrets:
  - name: wandb-mysql
---
# Source: wandb/charts/mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wandb-mysql
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.10.1
    app.kubernetes.io/instance: wandb
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mysql-root-password: "NW9Rdk9ZWEFrWA=="
  mysql-password: "d3IycGRaZWw0Sw=="
---
# Source: wandb/charts/mysql/templates/primary/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: wandb-mysql
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.10.1
    app.kubernetes.io/instance: wandb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
data:
  my.cnf: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    slow_query_log=0
    slow_query_log_file=/opt/bitnami/mysql/logs/mysqld.log
    long_query_time=10.0
    
    [client]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    
    [manager]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
---
# Source: wandb/charts/mysql/templates/primary/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: wandb-mysql-headless
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.10.1
    app.kubernetes.io/instance: wandb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector: 
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: wandb
    app.kubernetes.io/component: primary
---
# Source: wandb/charts/mysql/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: wandb-mysql
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.10.1
    app.kubernetes.io/instance: wandb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
  annotations:
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
      nodePort: null
  selector: 
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: wandb
    app.kubernetes.io/component: primary
---
# Source: wandb/charts/webservice/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wandb-webservice
  labels:
    
    helm.sh/chart: webservice-0.1.0
    app.kubernetes.io/name: webservice
    app.kubernetes.io/instance: wandb
    app.kubernetes.io/version: "0.33.0"
    wandb.com/webservice-name: webservice-0.1.0
    app.kubernetes.io/managed-by: Helm
    
  annotations:
    
spec:
  type: ClusterIP

  ports:
    - port: 8080
      targetPort: http-ws
      protocol: TCP
      name: http-ws
    - port: 8181
      targetPort: http-ws-prometheus
      protocol: TCP
      name: http-ws-prometheus

  selector:
    helm.sh/chart: webservice-0.1.0
    app.kubernetes.io/name: webservice
    app.kubernetes.io/instance: wandb
    app.kubernetes.io/version: "0.33.0"
    wandb.com/webservice-name: webservice-0.1.0
    app.kubernetes.io/managed-by: Helm
---
# Source: wandb/charts/webservice/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wandb-webservice
  labels:
    
    helm.sh/chart: webservice-0.1.0
    app.kubernetes.io/name: webservice
    app.kubernetes.io/instance: wandb
    app.kubernetes.io/version: "0.33.0"
    wandb.com/webservice-name: webservice-0.1.0
    app.kubernetes.io/managed-by: Helm
    
  annotations:
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webservice
      app.kubernetes.io/instance: wandb
      helm.sh/chart: webservice-0.1.0
      app.kubernetes.io/name: webservice
      app.kubernetes.io/instance: wandb
      app.kubernetes.io/version: "0.33.0"
      wandb.com/webservice-name: webservice-0.1.0
      app.kubernetes.io/managed-by: Helm

  template:
    metadata:
      labels:
        helm.sh/chart: webservice-0.1.0
        app.kubernetes.io/name: webservice
        app.kubernetes.io/instance: wandb
        app.kubernetes.io/version: "0.33.0"
        wandb.com/webservice-name: webservice-0.1.0
        app.kubernetes.io/managed-by: Helm
        
        
        

      annotations:

    spec:
      
      
      
      securityContext:
        runAsUser: 1000
        fsGroup: 1000      

      containers:
        - name: webservice
          
          image: "wandb/local:0.33.0"          
          imagePullPolicy: "Always"          

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: prometheus
              containerPort: 8181
              protocol: TCP
          
          env:
            - name: DATABASE_PORT
              value: "<nil>"
            - name: DATABASE_HOST
              value: "<nil>"
            - name: DATABASE
              value: "<nil>"
            - name: DATABASE_USER
              value: "<nil>"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "<nil>"
                  key:  MYSQL_PASSWORD
            - name: MYSQL
              value: "mysql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE)"
            - name: HOST
              value: http://localhost:8080
            
            

          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          startupProbe:
            httpGet:
              path: /ready
              port: http
            failureThreshold: 120

          resources:
            {}
---
# Source: wandb/charts/mysql/templates/primary/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wandb-mysql
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.10.1
    app.kubernetes.io/instance: wandb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
spec:
  replicas: 1
  podManagementPolicy: ""
  selector:
    matchLabels: 
      app.kubernetes.io/name: mysql
      app.kubernetes.io/instance: wandb
      app.kubernetes.io/component: primary
  serviceName: wandb-mysql
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/configuration: 513913115ee5de62b818a42a9186b6ebd788000b89ec85d48ec04110e32228c9
      labels:
        app.kubernetes.io/name: mysql
        helm.sh/chart: mysql-9.10.1
        app.kubernetes.io/instance: wandb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: primary
    spec:
      serviceAccountName: wandb-mysql
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: mysql
                    app.kubernetes.io/instance: wandb
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
      initContainers:
      containers:
        - name: mysql
          image: docker.io/bitnami/mysql:8.0.33-debian-11-r12
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wandb-mysql
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: "my_database"
          envFrom:
          ports:
            - name: mysql
              containerPort: 3306
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
                  fi
                  mysqladmin status -uroot -p"${password_aux}"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
                  fi
                  mysqladmin status -uroot -p"${password_aux}"
          startupProbe:
            failureThreshold: 10
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
                  fi
                  mysqladmin status -uroot -p"${password_aux}"
          resources: 
            limits: {}
            requests: {}
          volumeMounts:
            - name: data
              mountPath: /bitnami/mysql
            - name: config
              mountPath: /opt/bitnami/mysql/conf/my.cnf
              subPath: my.cnf
      volumes:
        - name: config
          configMap:
            name: wandb-mysql
  volumeClaimTemplates:
    - metadata:
        name: data
        labels: 
          app.kubernetes.io/name: mysql
          app.kubernetes.io/instance: wandb
          app.kubernetes.io/component: primary
        annotations:
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"

