# Default values for operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: wandb/operator
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

extraEnvs: []

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

podAnnotations: {}

nameOverride: "wandb"
fullnameOverride: ""

manager:
  debug:
    enabled: true
  serviceAccount:
    create: true
