apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: {{ include "name" }}-controller-manager-console-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 8080
      protocol: TCP
      targetPort: https
  selector:
    control-plane: controller-manager
