apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: {{ include "name" . }}-controller-manager-console-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: https
      port: 9090
      protocol: TCP
      targetPort: https
  selector:
    control-plane: controller-manager
