{{- if .Values.enabled }}
{{- $imageCfg := dict "global" $.Values.global.image "local" $.Values.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webservice.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "webservice.labels" . | nindent 4 }}
    {{- include "webservice.commonLabels" . | nindent 4 }}
    {{- if .Values.deployment.labels -}}
    {{-   toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "wandb.deploymentAnnotations" $ | nindent 4 }}
    {{- if .Values.deployment.annotations -}}
    {{-   toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wandb.selectorLabels" $ | nindent 6 }}
      {{- include "webservice.labels" . | nindent 6 }}

  {{- if .Values.deployment.strategy }}
  strategy:
    {{- .Values.deployment.strategy | toYaml | nindent 4 }}
  {{- end }}

  template:
    metadata:
      labels:
        {{- include "webservice.labels" . | nindent 8 }}
        {{- include "wandb.podLabels" . | nindent 8 }}
        {{- include "webservice.commonLabels" . | nindent 8 }}
        {{- include "webservice.podLabels" . | nindent 8 }}

      annotations:
        {{- if .Values.pod.annotations -}}
        {{-   toYaml .Values.pod.annotations | nindent 4 }}
        {{- end }}

    spec:
      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}
      
      {{- include "wandb.nodeSelector" . | nindent 6 }}
      {{- include "wandb.priorityClassName" . | nindent 6 }}
      {{- include "wandb.podSecurityContext" .Values.pod.securityContext | nindent 6 }}
      {{- include "wandb.image.pullSecrets" $imageCfg | indent 6 }}

      {{- if or .Values.serviceAccount.enabled .Values.global.serviceAccount.enabled }}
      serviceAccountName: {{ include "wandb.serviceAccount.name" . }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- include "wandb.image.pullPolicy" $imageCfg | indent 10 }}
          {{- include "wandb.containerSecurityContext" $ | indent 10 }}

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: prometheus
              containerPort: 8181
              protocol: TCP
          
          env:
            {{- if .Values.extraCors }}
            - name: GORILLA_CORS_ORIGINS
              value: {{ .Values.extraCors }}
            {{- end }}

            - name: MYSQL
              value: {{ "mysql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST)/$(DB)" }}
            - name: HOST
              value: {{ .Values.host  | default "http://localhost:8080" }}
            {{- include "webservice.extraEnv" (dict "global" .Values.global "local" .) | nindent 12 }}
            {{- include "wandb.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          startupProbe:
            httpGet:
              path: /ready
              port: http
            failureThreshold: 120

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}